name: Process Temporary Book

on:
  push:
    paths:
      - temp-book.json # فقط وقتی این فایل تغییر کنه، اجرا بشه

jobs:
  process-book:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read and process book file
        env:
          GH_TOKEN: ${{ secrets.AMULEO_TOKEN }} # اینجا سکرت فراخوانی می‌شه
        run: |
          echo "Reading temp-book.json..."
          BOOK_DATA=$(cat temp-book.json)
          echo "Processing book data: $BOOK_DATA"

      - name: Clean up temporary file
        run: rm temp-book.json
