name: Update Books JSON

on:
  workflow_dispatch:
    inputs:
      bookName:
        description: "نام کتاب"
        required: true
      bookAuthor:
        description: "نویسنده"
        required: true
      bookPages:
        description: "تعداد صفحات"
        required: true
      bookYear:
        description: "سال مطالعه"
        required: true

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Check if books.json exists
      run: |
        if [ ! -f books.json ]; then
          echo "Error: books.json does not exist in the root directory."
          exit 1
        fi

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Update books.json
      run: |
        BOOK_NAME="${{ github.event.inputs.bookName }}"
        BOOK_AUTHOR="${{ github.event.inputs.bookAuthor }}"
        BOOK_PAGES="${{ github.event.inputs.bookPages }}"
        BOOK_YEAR="${{ github.event.inputs.bookYear }}"

        jq --arg name "$BOOK_NAME" \
           --arg author "$BOOK_AUTHOR" \
           --arg pages "$BOOK_PAGES" \
           --arg year "$BOOK_YEAR" \
           '. += [{"name": $name, "author": $author, "pages": $pages | tonumber, "year": $year}]' \
           books.json > books_temp.json

        mv books_temp.json books.json

    - name: Commit Changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add books.json
        git commit -m "Added new book: ${{ github.event.inputs.bookName }}"
        git push
